### PR TITLE
Add confirm dialog for deleting gesture

### PR DESCRIPTION
**Pull request by microbit-robert**

### CODE REVIEW

**Comment by microbit-robert** [comment]
Is this really the only place we need a confirmation dialog?

**Comment by microbit-matt-hillsdon** [comment]
> 
Is this really the only place we need a confirmation dialog?

We have something similar for when new session deletes data but I can't think of another simple confirm example. Doesn't seem worth it for a recording.

**Comment by microbit-matt-hillsdon** [comment]
Maybe when resetting a MakeCode project to default?  Which itself might not be the best name.

**Comment by microbit-matt-hillsdon** [comment]
> Maybe when importing new data samples? At the moment, when we import a new JSON file, we overwrite what the user already has

Though perhaps that should be an option in a fancier three-way dialog.

**Comment by microbit-robert** [comment]
> > Maybe when importing new data samples? At the moment, when we import a new JSON file, we overwrite what the user already has
> 
> Though perhaps that should be an option in a fancier three-way dialog.

Are we imaging these three actions: Cancel; Save current data; Confirm?

**Comment by microbit-matt-hillsdon** [comment]
Let's just merge this one and then will review for any others. Pushed a merge of react into this branch.

**Review by microbit-matt-hillsdon — APPROVED** [review]

**Pull request merged**
