### PR TITLE
'total acc' filter bug fix, `abs()` wasn't performed on first element.

### PR DESCRIPTION
**Pull request by microbit-carlos**
I noticed that there was still differences between the total acceleration filter output from the device vs the browser, so I looked into this again.

Essentially, by leaving out the `initialValue` from `reduce(callbackFn, initialValue)` it uses the first element as `initialValue`, and in that case it does not apply `Math.abs()` to it.
And so, with arrays starting with a negative value it subtracted the first element from the total value instead of adding it.

### CODE REVIEW

**Comment by microbit-carlos** [comment]
As this affects the data going into the model the snapshot needs to be updated, not sure what the process is for this.
I assume I don't have to edit the `src/makecode/__snapshots__/utils.test.ts.snap` file manually? Do I just delete to get it to regenerate?

**Comment by microbit-carlos** [comment]
Okay, regenerated it following the instructions from https://vitest.dev/guide/snapshot and forced pushed the file into the branch.

**Review by microbit-robert — APPROVED** [review]
Good catch! LGTM.

**Comment by microbit-matt-hillsdon** [comment]
Thanks @microbit-carlos

**Pull request merged**
