### PR TITLE
Add pairing mode to micro:bit V2 BLE hex file.

### PR DESCRIPTION
**Pull request by microbit-carlos**
The BLE hex file for V2 (and therefore, the universal hex) doesn't have pairing mode enabled, which is needed to ensure the micro:bit can be reflashed from the mobile apps.
The V1 programme already had pairing mode enabled.

I've created this PR after a conversation with @jaustin, but we might need to confirm details before merging it, so this has been raised as a draft PR for visibility in the meantime.

A few of consideration about enabling pairing mode:
- It's hard to tell when the micro:bit might be in pairing mode, or running the programme and waiting to pair with the ML Tool
- The ML tool (and I assume ml-machine) is unable to finish a connection with a micro:bit in pairing mode, probably because in pairing mode the other services it expects are missing
- The current version of the ML Tool (and I assume ml-machine would as well) struggles to figure out what's happening if the micro:bit is put in pairing mode and the user tries to reconnect 
image

### CODE REVIEW

**Comment by jaustin** [comment]
Thanks Carlos, these are great points. I think we probably need to discuss it with Matt but it feels like pairing mode is important to have as this becomes more widespread so people can get their micro:bits back to MakeCode/Python using the apps.

Can we bring up appropriate services for pairing in BLE mode?

**Comment by jaustin** [comment]
...on further consideration, I think making ml-machine aware of pairing mode might be the simplest for a user - the similarity in what's on the display is definitely an issue, and I think one of the errors I saw in the Android app was because I'd connected (without pairing, I think) to the microbit while it had ml-machine code running.

@martinwork do you know if it's possible to construct a hex file that can have multiple services that don't require pairing, and then a way to trigger pairing that will persist for the bootloader?

**Comment by microbit-matt-hillsdon** [comment]
How can the UI tell?

**Comment by microbit-robert** [comment]
@microbit-carlos do you have steps to reproduce the double dialog scenario in the screenshot above?

**Comment by microbit-carlos** [comment]
> @microbit-carlos do you have steps to reproduce the double dialog scenario in the screenshot above?

I think this is how I triggered it:
- Flash the micro:bit with the included hex
- Connect to the ML Tool via BLE
- Put the micro:bit in pairing mode (this should disconnect from the ML Tool)
- Click reconnect, the modal seen in the background opens
- Wait a few seconds and the top modal appears for a few seconds (closes itself at some point)

**Comment by microbit-robert** [comment]
> > @microbit-carlos do you have steps to reproduce the double dialog scenario in the screenshot above?
> 
> I think this is how I triggered it:
> 
> * Flash the micro:bit with the included hex
> * Connect to the ML Tool via BLE
> * Put the micro:bit in pairing mode (this should disconnect from the ML Tool)
> * Click reconnect, the modal seen in the background opens
> * Wait a few seconds and the top modal appears for a few seconds (closes itself at some point)

I think I can fix the double dialog as it's own issue.

The error I get when the micro:bit is in pairing mode is `No Services matching UUID e95d0753-251d-470a-a062-fa1922dfa9a8 found in Device` rather than `Could not read model number`. I don't know why there is this discrepancy, so it's going to be hard to attribute a failure to connect to pairing mode unless anyone knows a good way of doing this already?

**Comment by martinwork** [comment]
> @martinwork do you know if it's possible to construct a hex file that can have multiple services that don't require pairing, and then a way to trigger pairing that will persist for the bootloader?

If prepared to modify CODAL. The services call 
https://github.com/lancaster-university/codal-microbit-v2/blob/d54ce9b784ef1bba22c075b281bb877abf53ea18/source/bluetooth/MicroBitAccelerometerService.cpp#L61

CreateCharacteristic uses the security defined in codal.json, but you could add CreateCharacteristicOpen, for example.
https://github.com/lancaster-university/codal-microbit-v2/blob/d54ce9b784ef1bba22c075b281bb877abf53ea18/source/bluetooth/MicroBitBLEService.cpp#L124

I just tried the iOS app. I was able to pair and flash over the ML hex, without needing Bluetooth pairing mode. There was some weirdness. A subsequent flash popped up the pairing dialogue, and needed a retry. That's expected because the app paired with open security, then flashed a hex with just works. I didn't test V1.

I used "universal-hex.hex".  For support purposes, I wonder if these hex files should have names that make them easily recognisable, Should it scroll ML, instead of the smiley, so we can recognise them in support emails?

**Comment by microbit-matt-hillsdon** [comment]
@microbit-robert this is M2 Mac connecting and then trying and failing to reconnect after going to pairing mode:

```
logging.ts:24 Bluetooth request device failed/cancelled
logError @ logging.ts:24
requestDevice @ MicrobitBluetooth.ts:540
await in requestDevice (async)
startBluetoothConnection @ MicrobitBluetooth.ts:494
assignBluetoothInput @ Microbits.ts:57
tryMicrobitBluetoothConnection @ ConnectDialogContainer.svelte:165
(anonymous) @ StandardButton.svelte:67
logging.ts:25 DOMException: User cancelled the requestDevice() chooser.
logError @ logging.ts:25
requestDevice @ MicrobitBluetooth.ts:540
await in requestDevice (async)
startBluetoothConnection @ MicrobitBluetooth.ts:494
assignBluetoothInput @ Microbits.ts:57
tryMicrobitBluetoothConnection @ ConnectDialogContainer.svelte:165
(anonymous) @ StandardButton.svelte:67
logging.ts:18 Bluetooth connect [1]
logging.ts:18 Bluetooth GATT server connected when connecting
logging.ts:18 Bluetooth GATT server promise field cleared
logging.ts:18 Bluetooth GATT server connected true
logging.ts:18 Bluetooth GATT disconnected... automatically trying reconnect
logging.ts:18 Bluetooth reconnect
logging.ts:18 Bluetooth connect [1]
logging.ts:18 Bluetooth GATT server connected when connecting
logging.ts:18 Bluetooth GATT server promise field cleared
logging.ts:18 Bluetooth GATT server connected true
logging.ts:24 Bluetooth connect error
logError @ logging.ts:24
connect @ MicrobitBluetooth.ts:172
await in connect (async)
reconnect @ MicrobitBluetooth.ts:225
MicrobitBluetooth.handleDisconnectEvent @ MicrobitBluetooth.ts:235
logging.ts:25 DOMException: No Services matching UUID e95d0753-251d-470a-a062-fa1922dfa9a8 found in Device.
logError @ logging.ts:25
connect @ MicrobitBluetooth.ts:172
await in connect (async)
reconnect @ MicrobitBluetooth.ts:225
MicrobitBluetooth.handleDisconnectEvent @ MicrobitBluetooth.ts:235
logging.ts:18 Bluetooth disconnect (programmatic)
logging.ts:18 Bluetooth GATT disconnect ignored during explicit disconnect
logging.ts:24 Bluetooth connect triggered by disconnect listener failed
logError @ logging.ts:24
MicrobitBluetooth.handleDisconnectEvent @ MicrobitBluetooth.ts:240
logging.ts:25 Error: Failed to establish a connection!
    at MicrobitBluetooth.connect (MicrobitBluetooth.ts:174:13)
    at async MicrobitBluetooth.reconnect (MicrobitBluetooth.ts:225:5)
    at async MicrobitBluetooth.handleDisconnectEvent (MicrobitBluetooth.ts:235:9)
logError @ logging.ts:25
MicrobitBluetooth.handleDisconnectEvent @ MicrobitBluetooth.ts:240
logging.ts:18 Bluetooth reconnect
logging.ts:18 Bluetooth connect [1]
logging.ts:18 Bluetooth GATT server connected when connecting
logging.ts:18 Bluetooth GATT server promise field cleared
logging.ts:18 Bluetooth GATT server connected true
logging.ts:24 Bluetooth connect error
logError @ logging.ts:24
connect @ MicrobitBluetooth.ts:172
await in connect (async)
reconnect @ MicrobitBluetooth.ts:225
reconnect @ Microbits.ts:95
reconnect @ reconnect.ts:37
handleReconnect @ ReconnectHelp.svelte:95
(anonymous) @ StandardButton.svelte:67
logging.ts:25 DOMException: No Services matching UUID e95d0753-251d-470a-a062-fa1922dfa9a8 found in Device.
logError @ logging.ts:25
connect @ MicrobitBluetooth.ts:172
await in connect (async)
reconnect @ MicrobitBluetooth.ts:225
reconnect @ Microbits.ts:95
reconnect @ reconnect.ts:37
handleReconnect @ ReconnectHelp.svelte:95
(anonymous) @ StandardButton.svelte:67
logging.ts:18 Bluetooth disconnect (programmatic)
logging.ts:18 Bluetooth GATT disconnect ignored during explicit disconnect
```

**Comment by microbit-matt-hillsdon** [comment]
From discussion with Jonny and Carlos this morning we agreed not to merge this because:

- We'd need to update the UI with new connection/reconnection advice and flows
- You can still flash a V2 from iOS with the current machine learning hex
- Radio bridge hexes already have pairing mode and the UI impact here is low because of restarts/flashing

So closing this. I'll leave the branch around in case we do want access to these hex files for testing.

We think the reconnect dialog with the advice list should have a suggestion to reset the device but at the moment that only benefits a radio remote in pairing mode so not a high priority (though might fix other issues too).

**Pull request closed without merging**
