### PR TITLE
Handle Connect btn for different connection status in ConnectToRecordDialog

### PR DESCRIPTION
**Pull request by microbit-grace**
- If not connected, connect button starts connection flow. 
- If needs reconnection, connect button reconnects.
- If it is reconnecting, connect button waits to reconnect and then closes dialog if successful.
- If already connected, connect button closes dialog.
- If a connection dialog opens, ConnectToRecord dialog closes.

https://microbit-global.monday.com/boards/1550536443/pulses/1666291687 (private)

### CODE REVIEW

**Comment by microbit-robert** [comment]
I've not looked at the code yet, but I've tested it out and all works as expected. 

It feels like these two scenarios should result in the same thing, either close the dialog or start the recording. Is there a reason they differ?

- If it is reconnecting, connect button waits to reconnect and then start recording if successful.
- If already connected, connect button closes dialog

**Comment by microbit-matt-hillsdon** [comment]
Discussed this with Grace. We agree they should be consistent but didn't feel very strongly which way. Decided that given record is a countdown timer it should probably only happen in response to a "record" type click. So "Connect" will just close the dialog once connected for both cases.

**Comment by microbit-grace** [comment]
Have updated the PR to so that if it is reconnecting, connect button waits to reconnect and then closes dialog if successful. [57b74ad](https://github.com/microbit-foundation/ml-trainer/pull/392/commits/57b74ad9e8428e80006cc4666512a35c6785d895)

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Pull request merged**
