### PR TITLE
Add ability to connect via bottom panel

### PR DESCRIPTION
**Pull request by microbit-robert**
- Don't redirect to home page on device disconnect
- Always show the bottom panel for the data and model (trained) pages
- Add ability to connect micro:bit using the full start flow from the bottom panel
- Keep live graph in motion at all times

We'll come back to simplified connection flows once the radio bridge code is in to reduce potential conflicts.

### CODE REVIEW

**Comment by microbit-grace** [comment]
https://reconnect.ml-trainer.pages.dev/

**Review by microbit-grace — CHANGES_REQUESTED** [review]
It's looking good. Haven't looked at the code yet, but saw that

1. When naming the first gesture, the horizontal scrollbar reappears
2. After disconnecting when there is no data, the vertical scrollbar appears and the connection flow seems to end abruptly (see screen video capture)
https://github.com/microbit-foundation/ml-trainer/assets/145345672/79b7b10a-9a08-4646-a457-a5de5b24eade

**Comment by microbit-robert** [comment]
> It's looking good. Haven't looked at the code yet, but saw that
> 
> 1. When naming the first gesture, the horizontal scrollbar reappears
> 2. After disconnecting when there is no data, the vertical scrollbar appears and the connection flow seems to end abruptly (see screen video capture: https://github.com/microbit-foundation/ml-trainer/assets/145345672/79b7b10a-9a08-4646-a457-a5de5b24eade)

Good spots:
- Fixed 1 in [4268fb5](https://github.com/microbit-foundation/ml-trainer/pull/136/commits/4268fb5d22f6f8dc928723944fb0cd2ba33c621b).
- Fixed 2 in [9c63210](https://github.com/microbit-foundation/ml-trainer/pull/136/commits/9c63210fdd6c6bbf49ff17c6148d83798d058686)

**Review by microbit-grace — APPROVED** [review]
LGTM

**Pull request merged**
