### PR TITLE
Ensure sensible tour cutout for code on testing page

### PR DESCRIPTION
**Pull request by microbit-robert**
See https://microbit-global.monday.com/boards/1550536443/views/16565217/pulses/1683700736 (private)

### CODE REVIEW

**Comment by microbit-robert** [comment]
New tour layout for default blocks:
image

New tour layout for user code blocks when height of blocks exceeds scrollable area:
image

**Review by microbit-grace — COMMENTED** [review]
Found this scenario, not sure what the fix is yet
Screenshot 2024-10-30 at 11 54 26

**Review by microbit-grace — APPROVED** [review]
Works well, LGTM, not sure if @microbit-matt-hillsdon have any suggestions

**Review by microbit-matt-hillsdon — APPROVED** [review]
LGTM

**Pull request merged**
