### PR TITLE
Start over if the initial connection fails twice

### PR DESCRIPTION
**Pull request by microbit-robert**
Reset state after failing to connect or reconnect twice.
Additional fix when the link micro:bit is unplugged and the tab is not in focus.
Additional fix for to ensure radio connect fail dialog specifies the correct micro:bit (link/remote).

### CODE REVIEW

**Comment by microbit-robert** [comment]
We currently get stuck with a "connecting..." dialog on the second failure. This needs testing thoroughly to ensure that there are no unforeseen side-effects.

**Review by microbit-grace — COMMENTED** [review]
Just tried the following for Bluetooth so far and here is what I got: 

- connect via bt - looks good
- tab switching - looks good
- failed to connect (unplug micro:bit whist connecting) - Looks good
- failed to connect twice (unplug micro:bit whist connecting, click connect) - Looks good  (got failed to reconnect twice dialog)
- bluetooth auto reconnect (Connect via bt, then click reset) - Looks good, reconnect successfully
- bluetooth connection loss dialog (Connect via bt, unplug micro:bit) - looks good
- bluetooth reconnect fail dialog (Connect via bt, disconnect, unplug micro:bit, click reconnect) - looks good
- bluetooth reconnect fail twice (connection loss/reconnect fail dialog, reconnect, get connect fail twice dialog) - looks good
- bluetooth connect after reconnect fail twice (get connect fail twice dialog, go through bt flow again) - I unexpectedly got a reconnect fail twice dialog  when needing to select micro:bit for bt. 

Screenshot 2024-11-15 at 09 18 27

Will have a go at radio bridge testing in a bit!

**Comment by microbit-robert** [comment]
> bluetooth connect after reconnect fail twice (get connect fail twice dialog, go through bt flow again) - I unexpectedly got a reconnect fail twice dialog when needing to select micro:bit for bt.

This happens on staging already and is not related to this change.

**Comment by microbit-grace** [comment]
> This happens on staging already and is not related to this change.

Oh interesting, I tried connection loss fail on staging and then went through the fail twice flow and didn't get the issue. I assumed it was working ok in staging. 

Just I tried it again, but this time with reconnect fail as the first failure and managed to recreate it in staging. Will add a task for it.

**Comment by microbit-grace** [comment]
> A fix for this problem. Everything probably needs retesting again. [576a891](https://github.com/microbit-foundation/ml-trainer/pull/500/commits/576a891edfb35df4fe2d15daf6ab94f188d68f1f)

Thanks bluetooth scenarios look good, will test radio bridge shortly

**Comment by microbit-grace** [comment]
For radio bridge,
- if I unplug the link micro:bit whilst connecting, I seem to be getting the fail twice start over reconnect dialog. 
- If I unplug the data collection micro:bit whilst connecting, I get a failed to connect to radio link micro:bit dialog. But when I switching tabs and returning back, the dialog disappears and it goes to reconnecting again

**Comment by microbit-grace** [comment]
> * if I unplug the link micro:bit whilst connecting, I seem to be getting the fail twice start over reconnect dialog.

Discussed with Rob and decided the scenario is not a problem.

> If I unplug the data collection micro:bit whilst connecting, I get a failed to connect to radio link micro:bit dialog. But when switching tabs and returning back, the dialog disappears and it goes to reconnecting again which eventually goes to connection loss I think

[8a04862](https://github.com/microbit-foundation/ml-trainer/pull/500/commits/8a048624b32131ee2d34dc595fec98d69b966f50)

**Comment by microbit-robert** [comment]
We think this is now in a good place.

**Review by microbit-matt-hillsdon — APPROVED** [review]

**Pull request merged**
