### PR TITLE
Update record button and add data samples status text

### PR DESCRIPTION
**Pull request by microbit-grace**
Notify users they need at least 3 data samples if they do not have enough in an action, otherwise show number of data samples for each action.

Screenshot 2024-10-25 at 13 52 17

### CODE REVIEW

**Comment by microbit-grace** [comment]
Not sure if the copy is right or too long. Suggestions welcomed

**Comment by microbit-matt-hillsdon** [comment]
From discussion with Giles:

Maybe "3 or more samples"

**Review by microbit-robert — APPROVED** [review]
LGTM. Holding off on merging until model issue has been resolved.

**Comment by microbit-matt-hillsdon** [comment]
There is still some debate over whether this UI is the right approach but it seems the more promising basis on which to build.
We now have a maintenance branch for the beta so that we can roll out bug fixes there independently of the UI experimentation.

**Pull request merged**
