### PR TITLE
Update serial protocol to use compact periodic messages.

### PR DESCRIPTION
**Pull request by microbit-carlos**
The radio hexes are updated with the compact periodic messages, which are now triggered with a different "start" command (from `START` to `ZSTART`). And the code updated to process this type of message instead of the original one.

The serial message has moved from: `P[213]AX[408]AY[748]AZ[-1288]BA[1]BB[1]`
to: `PD5998AEC2F83`

### CODE REVIEW

**Comment by microbit-carlos** [comment]
FYI @microbit-matt-hillsdon

**Comment by microbit-matt-hillsdon** [comment]
> FYI @microbit-matt-hillsdon

Thanks. Rob and Grace are taking an initial look at this.

**Comment by microbit-carlos** [comment]
PR is ready 👍

**Review by microbit-matt-hillsdon — APPROVED** [review]
This is working well.

**Pull request merged**
