### PR TITLE
Stop starting connection flow when starting new session

### PR DESCRIPTION
**Pull request by microbit-grace**

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
Holding off on merging this until we know if we can ship a model change as this breaks the video flow so has to wait for live.

**Comment by microbit-robert** [comment]
This change will also need applying to the import page https://github.com/microbit-foundation/ml-trainer/blob/main/src/pages/ImportPage.tsx#L82

**Comment by microbit-grace** [comment]
> This change will also need applying to the import page https://github.com/microbit-foundation/ml-trainer/blob/main/src/pages/ImportPage.tsx#L82

Good point! [0e91d60](https://github.com/microbit-foundation/ml-trainer/pull/423/commits/0e91d600f4ae8c5362142b94527a31bdaccfe98e)

**Review by microbit-matt-hillsdon — APPROVED** [review]
Less is more.

**Pull request merged**
