### PR TITLE
Flag for remote dev hex

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**

### CODE REVIEW

**Comment by microbit-carlos** [comment]
@microbit-matt-hillsdon @microbit-robert I've updated this branch/PR with the hex files 👍

**Comment by microbit-carlos** [comment]
Ups, added the wrong icon, will rebuild and update the hex files again.

**Comment by microbit-carlos** [comment]
The hex files have been updated, so this should be ready to be (squashed) merged.

**Review by microbit-robert — APPROVED** [review]
Tested with both flag values and no flag. All behave as expected. LGTM.

**Pull request merged**
