### PR TITLE
Improve MakeCode robustness

### PR DESCRIPTION
**Pull request by microbit-robert**
This is a fix for clicking on "Edit in MakeCode" as soon as possible after refreshing the "testing model" page which causes errors where MakeCode doesn't load properly and somehow destroys the user's code, or triggers a project import depending on whether the project had previously been opened in MakeCode or not.

If the project was generated by us, a mis-match in formatting was resulting in additional workspace save events as MakeCode updated the code. As a result, we got unexpected changes while MakeCode was open triggering a project import.

If the project has been edited, it was correctly formatted. However, after the workspace load event, we also needed to wait for the subsequent content load.

See https://microbit-global.monday.com/boards/1550536443/views/16565217/pulses/1703606502 (private)

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
Do we have any handle on what MakeCode is doing at this point? I think it'd be worth running with a local MakeCode and trying to add debug to get an idea (perhaps in makecode-embed).

**Comment by microbit-robert** [comment]
> Do we have any handle on what MakeCode is doing at this point? I think it'd be worth running with a local MakeCode and trying to add debug to get an idea (perhaps in makecode-embed).

I think that's the next step. While this hack seems to work OK in Chrome, it seems to end poorly in Firefox with a double "project loaded toast" appearing. Safe to say we don't merge this.

**Comment by microbit-robert** [comment]
This commit fixes the immediate click on "Edit in MakeCode" when the project is **not** the default [5e062f1](https://github.com/microbit-foundation/ml-trainer/pull/552/commits/5e062f14d639d53aaf57fb35505e40d8e846874b)

If the project is the default, we get the project loaded toast notification twice and a redirect to the data samples page. Investigating this discrepancy next.

**Comment by microbit-robert** [comment]
> This commit fixes the immediate click on "Edit in MakeCode" when the project is **not** the default [5e062f1](https://github.com/microbit-foundation/ml-trainer/pull/552/commits/5e062f14d639d53aaf57fb35505e40d8e846874b)
> 
> If the project is the default, we get the project loaded toast notification twice and a redirect to the data samples page. Investigating this discrepancy next.

MakeCode was doing a bunch of workspace saves when the code was not in the expected style. This meant we got unexpected changes while MakeCode was open (workspace load and content load had already succeeded) which caused us to think that a project import had occured. Fix [23a991d](https://github.com/microbit-foundation/ml-trainer/pull/552/commits/23a991dc884a70cea93cfad8a32b0ab46ca2c191)

**Pull request merged**
